#!/bin/sh

# some (+/-1%) photos from iPhoto used to upload to NextCloud and OwnCloud with a .(null) extention. 
# This script renames all files with the `.(null)` extension to `.jpg`.

for file in *."(null)"; do
  # Rename the file in place.
  mv -i "$file" "${file%."(null)"}.jpg"
done

echo "Done."

